description: Jekyll theme compatible with GitHub Pages

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-readme-index
  - jekyll-github-metadata

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec

# Where things are
source: .
theme: null
collections_dir: .
collections:
  posts:
    output: true
destination: ./_site

# Front Matter Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
